### ISSUE TITLE
[BUG] 사진첩 파일 경로 404 에러

### ISSUE THREAD

**Issue by spy03128** [SAMMaru5/SAMMaruServer#5]
## 📌 문제 상황

사진첩에서 파일을 작성하면 바로 반영이 안됩니다.
Docker를 껐다가 켜야지만 파일 경로가 제대로 인식되어서 파일이 뜹니다.
그 전에는 파일을 찾을 수 없다는 404 에러가 발생합니다.

## 🐛 발생 위치

http://localhost:3000/photo

### 🚨 참고 스크린 샷

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/57143818/167304843-23942212-656d-40c1-ae9f-2df827c1db89.png">

- 추가적인 공유가 필요한 사항은 Comment

**Comment by chiyongs** [comment]
https://github.com/SAMMaru5/SAMMaruClient/issues/15 해당 이슈 완료 후 자세한 내용을 알 수 있을 것 같습니다.

**Comment by chiyongs** [comment]
https://github.com/SAMMaru5/SAMMaruClient/issues/15
이슈 해결되었습니다.

**Comment by chiyongs** [comment]
파일다운로드 API가 아닌 게시글 수정 API의 권한을 변경해서 수정해서 다시 푸쉬하겠습니다.
